name: Java CI

on:
  schedule:
    - cron: "0 1 * * *"  # Runs every day at 1:00 AM UTC ( 7:00 AM UTC+6 )
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Maven dependencies
        uses: actions/cache@v3  # Updated to v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml  # Skip tests during build

      - name: Ensure Downloads Directory Exists
        run: mkdir -p $GITHUB_WORKSPACE/downloads

      - name: Run Cucumber tests with JUnit
        run: mvn -B test -Dtest=runners.TestRunner
        continue-on-error: true  # Continue even if tests fail


      - name: Upload Cucumber HTML report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-reports
          path: target/cucumber-html-report.html

      - name: List Downloaded Files
        run: ls -al $GITHUB_WORKSPACE/downloads

      - name: Upload Downloaded Files
        uses: actions/upload-artifact@v4
        with:
          name: workspace-files
          path: /Users/runner/work/Cucumber_maven/Cucumber_maven/downloads/*

      # Send email with the artifact download link
      - name: Send test result email
        uses: dawidd6/action-send-mail@v3
        with:
          from: ${{ secrets.EMAIL_USERNAME }}
          to: ${{ secrets.RECIPIENT_EMAIL }},${{ secrets.RECIPIENT_EMAIL_2 }},${{ secrets.RECIPIENT_EMAIL_3 }},${{ secrets.RECIPIENT_EMAIL_4 }},${{ secrets.RECIPIENT_EMAIL_5 }},${{ secrets.RECIPIENT_EMAIL_6 }}
          subject: "ABBL Smoke Test Results"
          body: |
            Hello,

            The AB Retail Web Smoke test run has completed. You can download the HTML report and Transactions Receipt here:

            [View GitHub Actions Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

          server_address: smtp.gmail.com  # Correct parameter for SMTP server
          server_port: 587  # Correct parameter for SMTP port
          username: ${{ secrets.EMAIL_USERNAME }}  # Correct parameter for SMTP username
          password: ${{ secrets.EMAIL_PASSWORD }}  # Correct parameter for SMTP password

      - name: Send notification to the Teams
        run: |
          curl -H "Content-Type: application/json" -d '{
            "title": "Cucumber Test Run Completed",
            "text": "The AB Retail Web Smoke test run has completed. You can download the HTML report here: [View GitHub Actions Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          }' ${{ secrets.TEAMS_WEBHOOK_URL }}
