name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Maven dependencies
        uses: actions/cache@v3  # Updated to v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml  # Skip tests during build

      - name: Run Cucumber tests with JUnit
        run: mvn -B test -Dtest=runners.TestRunner
        continue-on-error: true  # Continue even if tests fail


      - name: Upload Cucumber HTML report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-reports
          path: target/cucumber-html-report.html

      - name: Get Artifact ID from GitHub API
        id: get_artifact_id
        run: |
            # Use GitHub API to get artifact ID
            artifact_url="https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts"
            response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" $artifact_url)
            artifact_id=$(echo $response | jq -r '.[0].id')  # Get the ID of the first artifact
            echo "Artifact ID: $artifact_id"
            echo "artifact_id=$artifact_id" >> $GITHUB_ENV  # Set the artifact ID as an environment variable


      # Send email with the artifact download link
      - name: Send test result email
        uses: dawidd6/action-send-mail@v3
        with:
          from: ${{ secrets.EMAIL_USERNAME }}
          to: ${{ secrets.RECIPIENT_EMAIL }}
          subject: "Cucumber Test Results"
          body: |
            Hello,

            The AB Retail Web Smoke test run has completed. You can download the HTML report here:

            [Download Cucumber HTML Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ env.artifact_id }})

          server_address: smtp.gmail.com  # Correct parameter for SMTP server
          server_port: 587  # Correct parameter for SMTP port
          username: ${{ secrets.EMAIL_USERNAME }}  # Correct parameter for SMTP username
          password: ${{ secrets.EMAIL_PASSWORD }}  # Correct parameter for SMTP password

