name: Java CI

on:
  workflow_dispatch:    # Allows manual trigger
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml

      - name: Ensure Downloads Directory Exists
        run: mkdir -p $GITHUB_WORKSPACE/downloads

      - name: Run Cucumber tests with JUnit
        run: mvn -B test -Dtest=runners.TestRunner
        continue-on-error: true

      - name: Upload Cucumber HTML report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-reports
          path: target/cucumber-html-report.html

      - name: List Downloaded Files
        run: ls -al $GITHUB_WORKSPACE/downloads

      - name: Upload Downloaded Files
        uses: actions/upload-artifact@v4
        with:
          name: workspace-files
          path: $GITHUB_WORKSPACE/downloads/*
